// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyDgJoaa0IeP_UgGyiy5y-hRYgDD7RfS154",
  authDomain: "capstone-ca5d5.firebaseapp.com",
  databaseURL: "https://capstone-ca5d5-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "capstone-ca5d5",
  storageBucket: "capstone-ca5d5.firebasestorage.app",
  messagingSenderId: "499691183216",
  appId: "1:499691183216:web:93392b331aab6a776828b5",
  measurementId: "G-MF3YD1PZY9"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhE73f9Kz6X14llzsEa9lERYpJgxvVhw',
    appId: '1:499691183216:android:e8d91617e5d6e90d6828b5',
    messagingSenderId: '499691183216',
    projectId: 'capstone-ca5d5',
    databaseURL: 'https://capstone-ca5d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstone-ca5d5.firebasestorage.app',
  );
}

