// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvRVetb6lZzxpIQQ8gqIGK1J2WOlBnok',
    appId: '1:755339267599:web:a641b5b447491be4e01d7a',
    messagingSenderId: '755339267599',
    projectId: 'passenger-signuplogin',
    authDomain: 'passenger-signuplogin.firebaseapp.com',
    databaseURL: 'https://passenger-signuplogin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'passenger-signuplogin.appspot.com',
    measurementId: 'G-SRDZDG7GW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLt8ILMXSFRP12xS8P7830kGNBeGn47s',
    appId: '1:755339267599:android:13c3d99ae54b15d2e01d7a',
    messagingSenderId: '755339267599',
    projectId: 'passenger-signuplogin',
    databaseURL: 'https://passenger-signuplogin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'passenger-signuplogin.appspot.com',
  );
}
